AkiToyWeb/Models/Producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkiToyWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        [DisplayName("Codigo del producto")]
        public int idProducto { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Detalle { get; set; }
        [DisplayName("Precio costo")]
        [Required]
        [Range(0, float.MaxValue, ErrorMessage = "Please enter valid a Number")]
        public Nullable<decimal> PrecioCosto { get; set; }
        
        [DisplayName("Precio de venta")]
        [Required]
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        [Required]
        public Nullable<int> Stock { get; set; }
        [DisplayName("Fecha de registro")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        [DisplayName("Fecha de lanzamiento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaLanzamiento { get; set; }
        [DisplayName("Peso en Kg.")]
        public Nullable<decimal> Peso { get; set; }
        [DisplayName("Altura en mm.")]
        public string Dimensiones { get; set; }
        [DisplayName("Marca")]
        public Nullable<int> idMarca { get; set; }
        [DisplayName("Estado del producto")]
        public Nullable<int> idEstado { get; set; }
        [DisplayName("Serie")]
        public Nullable<int> idSerie { get; set; }
        [DisplayName("Linea")]
        public Nullable<int> idLinea { get; set; }
        [DisplayName("Categoria")]
        public Nullable<int> idCategoria { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public Nullable<int> EliminadorPor { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Linea Linea { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Serie Serie { get; set; }

        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}

AkiToyWeb/Controllers/ProductoController.cs
using AkiToyWeb.Datos;
using AkiToyWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AkiToyWeb.Controllers
{
    public class ProductoController : Controller
    {
        private ProductoAdmin productoAdmin = new ProductoAdmin();
        private MarcaAdmin marca = new MarcaAdmin();
        private EstadoAdmin estado = new EstadoAdmin();
        private CategoriaAdmin categoria = new CategoriaAdmin();
        private LineaAdmin linea = new LineaAdmin();
        private SerieAdmin serie = new SerieAdmin();

        // GET: Producto
        public ActionResult Index()
        {
           return View(productoAdmin.Consultar());
        }

        public ActionResult Detalle(int id)
        {
            //return View(productoAdmin.Consultar(id));
            using (AkiToyEntities contexto = new AkiToyEntities())
            {
                var model = productoAdmin.Consultar(id);
                return View(model);
            }            
        }

        public ActionResult Crear()
        {
            ViewBag.Series = serie.ComboBoxSeries();
            ViewBag.Lineas = linea.ComboBoxLineas();
            ViewBag.Estados = estado.ComboBoxEstados();
            ViewBag.Categorias = categoria.ComboBoxCategorias();
            ViewBag.Marcas = marca.ComboBoxMarcas();
            /*ViewData["fechaActual"] = DateTime.Now.ToString();*/
            return View();
            
                
        }

        public ActionResult Guardar(Producto producto)
        {
            productoAdmin.Guardar(producto);
            
            return View("Index" , productoAdmin.Consultar());
        }

        public ActionResult Editar(int id)
        {
            ViewBag.Series = serie.ComboBoxSeries();
            ViewBag.Lineas = linea.ComboBoxLineas();
            ViewBag.Estados = estado.ComboBoxEstados();
            ViewBag.Categorias = categoria.ComboBoxCategorias();
            ViewBag.Marcas = marca.ComboBoxMarcas();
            return View(productoAdmin.Consultar(id));
        }

        public ActionResult Modificar(Producto producto)
        {
            productoAdmin.Modificar(producto);
            return View("Index", productoAdmin.Consultar());
        }

        public ActionResult Eliminar(int id)
        {
            if (id != null)
            {
                Producto producto = productoAdmin.Consultar(id);
                productoAdmin.Eliminar(producto);
            }
            return View("Index", productoAdmin.Consultar());
            
        }

    }

}

AkiToyWeb/Views/Producto/Crear.cshtml
@model AkiToyWeb.Models.Producto

@{
    ViewBag.Title = "Registrar nuevo producto";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container" style="padding-top: 60px">
    <div style="padding-bottom: 10px">

        <h2>Registar nuevo producto</h2>
    </div>
</div>

<div class="container">

    @using (Html.BeginForm("Guardar", "Producto", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioCosto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioCosto, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.PrecioCosto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioVenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioVenta, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.PrecioVenta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descuento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descuento, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Descuento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaIngreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.FechaIngreso, new { @Value = @DateTime.Now.ToShortDateString(), @class = "form-control", @readonly="readonly" } )
                @Html.ValidationMessageFor(model => model.FechaLanzamiento, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.FechaLanzamiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaLanzamiento, new { htmlAttributes = new { @class = "form-control", type = "date", required = "required" } })
                @Html.ValidationMessageFor(model => model.FechaLanzamiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dimensiones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dimensiones, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Dimensiones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Marca:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idMarca, ViewBag.Marcas as SelectList, "Seleccionar marca", new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idMarca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Estado:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idEstado, ViewBag.Estados as SelectList, "Seleccionar estado", new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idEstado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Serie:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idSerie, ViewBag.Series as SelectList, "Seleccionar serie", new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idSerie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Linea:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idLinea, ViewBag.Lineas as SelectList, "Seleccionar linea", new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idLinea, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Categoria:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idCategoria, ViewBag.Categorias as SelectList, "Seleccionar categoria", new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Regresar a la lista", "Index")
    </div>
</div>

AkiToyWeb/Views/Producto/Detalle.cshtml
@model AkiToyWeb.Models.Producto

@{
    ViewBag.Title = "Detalles del producto";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

    <div class="container" style="padding-top: 60px">
        <div style="padding-bottom: 10px">
            
                <h2>@Model.Nombre</h2>
    </div>
    </div>
        <div class="container">
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayName("Codigo del producto")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.idProducto)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Nombre)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Detalle)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Detalle)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PrecioCosto)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PrecioCosto)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PrecioVenta)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PrecioVenta)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Descuento)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Descuento)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Stock)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Stock)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FechaIngreso)
                </dt>

                <dd>
                    @if(Model.FechaIngreso != null) {@Model.FechaIngreso.Value.ToString("dd/MM/yyyy")}
                    else{@Html.DisplayFor(Model => Model.FechaIngreso)}
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FechaLanzamiento)
                </dt>

                <dd>
                    @if(Model.FechaLanzamiento != null) {@Model.FechaLanzamiento.Value.ToString("MMMM yyyy")}
                    else {@Html.DisplayFor(Model => Model.FechaLanzamiento)}
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Peso)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Peso)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Dimensiones)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Dimensiones)
                </dd>

                <dt>
                    @Html.DisplayName("Marca")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Marca.Detalle)
                </dd>

                <dt>
                    @Html.DisplayName("Estado")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Estado.Detalle)
                </dd>

                <dt>
                    @Html.DisplayName("Serie")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Serie.Detalle)
                </dd>

                <dt>
                    @Html.DisplayName("Linea")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Linea.Detalle)
                </dd>

                <dt>
                    @Html.DisplayName("Categoria")
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Categoria.Detalle)
                </dd>

            </dl>
        </div>

        <div class="container">
            <p>
                @Html.ActionLink("Editar", "Editar", new { id = Model.idProducto }) |
                @Html.ActionLink("Regresar a la lista", "Index")
            </p>

        </div>
    

AkiToyWeb/Views/Producto/Editar.cshtml
@model AkiToyWeb.Models.Producto

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container" style="padding-top: 60px">
    <div style="padding-bottom: 10px">

        <h2>@Model.Nombre</h2>
    </div>
</div>

<div class="container">

    @using (Html.BeginForm("Modificar", "Producto", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idProducto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idProducto, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.idProducto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioCosto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioCosto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioCosto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioVenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioVenta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioVenta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descuento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descuento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descuento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaIngreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaIngreso, new { htmlAttributes = new { @class = "form-control", @readonly="readonly" } })
                @Html.ValidationMessageFor(model => model.FechaIngreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaLanzamiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaLanzamiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaLanzamiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dimensiones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dimensiones, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dimensiones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Marca:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idMarca, ViewBag.Marcas as SelectList, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idMarca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Estado:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idEstado, ViewBag.Estados as SelectList, "Seleccionar estado", new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idEstado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Serie:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idSerie, ViewBag.Series as SelectList, "Seleccionar serie", new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idSerie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Linea:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idLinea, ViewBag.Lineas as SelectList, "Seleccionar linea", new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idLinea, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Categoria:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idCategoria, ViewBag.Categorias as SelectList, "Seleccionar categoria", new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.idCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>

AkiToyWeb/Views/Producto/Index.cshtml
@model IEnumerable<AkiToyWeb.Models.Producto>

@{
    ViewBag.Title = "Akitoy - Productos registrados";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

    <div class="home2">
        <div class="home_container">
            <div class="home_content">
                <div class="home_title2">Productos registrados</div>
                <div class="breadcrumbs">
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <a href="@Url.Action("Crear" , "Producto") " class="btn btn-primary"><i class="fas fa-plus"> Nuevo Producto</i></a>
    </div>
    <br />
    <br />
    <div class="container table-responsive">
        <table class="table table-striped" cellspacing="0" width="100%" id="example">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayName("ID")
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PrecioVenta)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Stock)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Marca)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Estado)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Serie)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Linea)
                    </th>
                    <th class="text-nowrap"></th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.idProducto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PrecioVenta)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Stock)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Marca.Detalle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado.Detalle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Serie.Detalle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Linea.Detalle)
                    </td>
                    <td class="text-nowrap">
                        <a href="@Url.Action("Detalle" , "Producto", new { id = item.idProducto } ) " class="btn btn-success"><i class="fas fa-eye"> </i></a>
                        <a href="@Url.Action("Editar" , "Producto", new { id = item.idProducto }) " class="btn btn-primary"><i class="fas fa-edit"> </i></a>
                        <a href="@Url.Action("Eliminar" , "Producto",new { id = item.idProducto } ) " class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
            }

        </table>
    </div>